# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61mera_service.proto\x12\rcameraService\x1a\x1bgoogle/protobuf/empty.proto\")\n\x15IsCameraAliveResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\".\n\x1bGetInstalledModulesResponse\x12\x0f\n\x07modules\x18\x01 \x03(\t\"?\n\x15InstallModulesRequest\x12&\n\x07modules\x18\x01 \x03(\x0b\x32\x15.cameraService.Module\"\'\n\x06Module\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"%\n\x13GetLastFrameRequest\x12\x0e\n\x06module\x18\x01 \x01(\t\"\x16\n\x05\x46rame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x32\xf8\x01\n\rCameraService\x12M\n\rIsCameraAlive\x12\x16.google.protobuf.Empty\x1a$.cameraService.IsCameraAliveResponse\x12N\n\x0eInstallModules\x12$.cameraService.InstallModulesRequest\x1a\x16.google.protobuf.Empty\x12H\n\x0cGetLastFrame\x12\".cameraService.GetLastFrameRequest\x1a\x14.cameraService.Frameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISCAMERAALIVERESPONSE']._serialized_start=68
  _globals['_ISCAMERAALIVERESPONSE']._serialized_end=109
  _globals['_GETINSTALLEDMODULESRESPONSE']._serialized_start=111
  _globals['_GETINSTALLEDMODULESRESPONSE']._serialized_end=157
  _globals['_INSTALLMODULESREQUEST']._serialized_start=159
  _globals['_INSTALLMODULESREQUEST']._serialized_end=222
  _globals['_MODULE']._serialized_start=224
  _globals['_MODULE']._serialized_end=263
  _globals['_GETLASTFRAMEREQUEST']._serialized_start=265
  _globals['_GETLASTFRAMEREQUEST']._serialized_end=302
  _globals['_FRAME']._serialized_start=304
  _globals['_FRAME']._serialized_end=326
  _globals['_CAMERASERVICE']._serialized_start=329
  _globals['_CAMERASERVICE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
