// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "camera-service.proto" (package "cameraService", syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message cameraService.IsCameraAliveResponse
 */
export interface IsCameraAliveResponse {
    /**
     * @generated from protobuf field: bool isAlive = 1;
     */
    isAlive: boolean;
}
/**
 * @generated from protobuf message cameraService.GetInstalledModulesResponse
 */
export interface GetInstalledModulesResponse {
    /**
     * @generated from protobuf field: repeated string modules = 1;
     */
    modules: string[];
}
/**
 * @generated from protobuf message cameraService.InstallModulesRequest
 */
export interface InstallModulesRequest {
    /**
     * @generated from protobuf field: repeated string modules = 1;
     */
    modules: string[];
}
// @generated message type with reflection information, may provide speed optimized methods
class IsCameraAliveResponse$Type extends MessageType<IsCameraAliveResponse> {
    constructor() {
        super("cameraService.IsCameraAliveResponse", [
            { no: 1, name: "isAlive", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<IsCameraAliveResponse>): IsCameraAliveResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isAlive = false;
        if (value !== undefined)
            reflectionMergePartial<IsCameraAliveResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsCameraAliveResponse): IsCameraAliveResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool isAlive */ 1:
                    message.isAlive = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsCameraAliveResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool isAlive = 1; */
        if (message.isAlive !== false)
            writer.tag(1, WireType.Varint).bool(message.isAlive);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cameraService.IsCameraAliveResponse
 */
export const IsCameraAliveResponse = new IsCameraAliveResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetInstalledModulesResponse$Type extends MessageType<GetInstalledModulesResponse> {
    constructor() {
        super("cameraService.GetInstalledModulesResponse", [
            { no: 1, name: "modules", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetInstalledModulesResponse>): GetInstalledModulesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.modules = [];
        if (value !== undefined)
            reflectionMergePartial<GetInstalledModulesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetInstalledModulesResponse): GetInstalledModulesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string modules */ 1:
                    message.modules.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetInstalledModulesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string modules = 1; */
        for (let i = 0; i < message.modules.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.modules[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cameraService.GetInstalledModulesResponse
 */
export const GetInstalledModulesResponse = new GetInstalledModulesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InstallModulesRequest$Type extends MessageType<InstallModulesRequest> {
    constructor() {
        super("cameraService.InstallModulesRequest", [
            { no: 1, name: "modules", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InstallModulesRequest>): InstallModulesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.modules = [];
        if (value !== undefined)
            reflectionMergePartial<InstallModulesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InstallModulesRequest): InstallModulesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string modules */ 1:
                    message.modules.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InstallModulesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string modules = 1; */
        for (let i = 0; i < message.modules.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.modules[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message cameraService.InstallModulesRequest
 */
export const InstallModulesRequest = new InstallModulesRequest$Type();
/**
 * @generated ServiceType for protobuf service cameraService.CameraService
 */
export const CameraService = new ServiceType("cameraService.CameraService", [
    { name: "IsCameraAlive", options: {}, I: Empty, O: IsCameraAliveResponse },
    { name: "GetInstalledModules", options: {}, I: Empty, O: GetInstalledModulesResponse },
    { name: "InstallModules", options: {}, I: InstallModulesRequest, O: Empty }
]);
